// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvjezJPs22jYsbwM5jTgA6lLo0kwheG8A',
    appId: '1:1084248724336:web:1b2cea48580cb4db16f5b5',
    messagingSenderId: '1084248724336',
    projectId: 'mantis-bca8d',
    authDomain: 'mantis-bca8d.firebaseapp.com',
    databaseURL: 'https://mantis-bca8d.firebaseio.com',
    storageBucket: 'mantis-bca8d.firebasestorage.app',
    measurementId: 'G-E217D8TTFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm9uGtNEvTDyhZ5HqSMnP9Fx0w7a_54hs',
    appId: '1:1084248724336:android:c0f325c9f7fb2e4216f5b5',
    messagingSenderId: '1084248724336',
    projectId: 'mantis-bca8d',
    databaseURL: 'https://mantis-bca8d.firebaseio.com',
    storageBucket: 'mantis-bca8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAC2YzQ0f8bwRZVtQH40AsNqJ-7Y_n1wM',
    appId: '1:1084248724336:ios:d127cdd80bdd7c5316f5b5',
    messagingSenderId: '1084248724336',
    projectId: 'mantis-bca8d',
    databaseURL: 'https://mantis-bca8d.firebaseio.com',
    storageBucket: 'mantis-bca8d.firebasestorage.app',
    iosBundleId: 'com.ecosat.mantiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAC2YzQ0f8bwRZVtQH40AsNqJ-7Y_n1wM',
    appId: '1:1084248724336:ios:d127cdd80bdd7c5316f5b5',
    messagingSenderId: '1084248724336',
    projectId: 'mantis-bca8d',
    databaseURL: 'https://mantis-bca8d.firebaseio.com',
    storageBucket: 'mantis-bca8d.firebasestorage.app',
    iosBundleId: 'com.ecosat.mantiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvjezJPs22jYsbwM5jTgA6lLo0kwheG8A',
    appId: '1:1084248724336:web:e4f50fb7cb06f69c16f5b5',
    messagingSenderId: '1084248724336',
    projectId: 'mantis-bca8d',
    authDomain: 'mantis-bca8d.firebaseapp.com',
    databaseURL: 'https://mantis-bca8d.firebaseio.com',
    storageBucket: 'mantis-bca8d.firebasestorage.app',
    measurementId: 'G-D33ZQK0H8L',
  );

}